# WIP
name: .NET CLI App Build and Test
on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --configuration Release --no-restore
    - name: Test project
      run: dotnet test --no-restore --verbosity normal
    - name: Run application
      run: dotnet C:\actions-runner\_work\TestLocalRunnerRepo\TestLocalRunnerRepo\bin\Release\net8.0\TestLocalRunnerRepo.exe
